name: hapc-ocsr
channels:
  - defaults
dependencies:
  - python=3.8
  - tk
  - pip:
    - torch==2.0.1
    - rdkit==2023.9.1
    - rdkit-pypi==2022.9.5
    - numpy==1.24.3
    - networkx==3.1
    - Pillow
    - pandas
    - matplotlib
    - tensorboardX
    - opencv-python==4.8.0.76
    - opencv-python-headless==4.8.0.76
    - scikit-learn<1.4.0
    - transformers==4.33.1
    - sentencepiece<0.2.0
    - SmilesPE==0.0.3
    - OpenNMT-py==2.2.0
    - albumentations==1.1.0
    - timm==0.5.4
  